package Car;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
   public Login() {
    initComponents();

    // Make jPanel1 fill the whole frame
   
  
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        UnameTb = new javax.swing.JTextField();
        Show = new javax.swing.JLabel();
        Hide = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PwordTb = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 102), 2));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(80000000, 50000000));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel2.setPreferredSize(new java.awt.Dimension(365, 503));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CAR RENTAL SYSTEM");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 0, 320, 90);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Smart Price");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(150, 440, 100, 17);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Smooth Rides");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(140, 420, 120, 17);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageR/cars login.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 10, 340, 480);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("LOGIN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 170, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("User ID:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 70, -1));

        UnameTb.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        UnameTb.setForeground(new java.awt.Color(51, 51, 51));
        UnameTb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UnameTbKeyPressed(evt);
            }
        });
        jPanel1.add(UnameTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 350, 40));

        Show.setBackground(new java.awt.Color(255, 255, 255));
        Show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageR/Untitled-1.png"))); // NOI18N
        Show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ShowMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ShowMouseReleased(evt);
            }
        });
        jPanel1.add(Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, 30, 40));

        Hide.setBackground(new java.awt.Color(255, 255, 255));
        Hide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImageR/Untitled-2.png"))); // NOI18N
        Hide.setDisabledIcon(null);
        Hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HideMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                HideMouseReleased(evt);
            }
        });
        jPanel1.add(Hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, 30, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Password:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 90, -1));

        PwordTb.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        PwordTb.setForeground(new java.awt.Color(51, 51, 51));
        PwordTb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PwordTbKeyPressed(evt);
            }
        });
        jPanel1.add(PwordTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 350, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 120, 51));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(230, 0, 52));
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 503));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


private void __storeOriginalBoundsDirectChildren(java.awt.Container root) {
    for (java.awt.Component child : root.getComponents()) {
        if (child instanceof javax.swing.JComponent) {
            ((javax.swing.JComponent) child).putClientProperty("origBounds", child.getBounds());
        }
    }
}

private void __scaleDirectChildren(java.awt.Container root, java.awt.Dimension design) {
    if (design.width <= 0 || design.height <= 0) return;

    double sx = root.getWidth()  / (double) design.width;
    double sy = root.getHeight() / (double) design.height;

    for (java.awt.Component child : root.getComponents()) {
        if (child instanceof javax.swing.JComponent) {
            Object prop = ((javax.swing.JComponent) child).getClientProperty("origBounds");
            if (prop instanceof java.awt.Rectangle) {
                java.awt.Rectangle r = (java.awt.Rectangle) prop;
                child.setBounds(
                    (int) Math.round(r.x * sx),
                    (int) Math.round(r.y * sy),
                    (int) Math.round(r.width * sx),
                    (int) Math.round(r.height * sy)
                );
            }
        }
    }
    root.validate();
    root.repaint();
}
/* === END AUTO FULL-SCREEN + SCALING === */
    private void UnameTbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UnameTbKeyPressed
        
        int key=evt.getKeyCode();
        if (key==10){
            PwordTb.requestFocus();
        }
    }//GEN-LAST:event_UnameTbKeyPressed

    private void HideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HideMousePressed
        Show.setVisible(true);
        Hide.setVisible(false);
        PwordTb.setEchoChar('*');
    }//GEN-LAST:event_HideMousePressed

    private void HideMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HideMouseReleased

    }//GEN-LAST:event_HideMouseReleased

    private void ShowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMousePressed
        Hide.setVisible(true);
        Show.setVisible(false);
        PwordTb.setEchoChar((char)0);
    }//GEN-LAST:event_ShowMousePressed

    private void ShowMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMouseReleased

    }//GEN-LAST:event_ShowMouseReleased

    private void PwordTbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PwordTbKeyPressed
  int key = evt.getKeyCode();
    if (key == KeyEvent.VK_ENTER) {
        jButton1.doClick(); // Simulates pressing the Add New button
            }
    }//GEN-LAST:event_PwordTbKeyPressed
/*
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String Id, Password, query, passDb = null;
String SUrl, SUser, Spass;
SUrl = "jdbc:MySQL://localhost:3306/java__users_database";
SUser = "root";
Spass = "";
int notFound = 0;

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection(SUrl, SUser, Spass);
    Statement st = con.createStatement();

    if ("".equals(UnameTb.getText())) {
        JOptionPane.showMessageDialog(new JFrame(), "User id is required", "Error", JOptionPane.ERROR_MESSAGE);
    } else if ("".equals(PwordTb.getText())) {
        JOptionPane.showMessageDialog(new JFrame(), "Password is required", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
        Id = UnameTb.getText();
        Password = PwordTb.getText();

        query = "SELECT * FROM user WHERE ID='" + Id + "'";
        ResultSet rs = st.executeQuery(query);

        while (rs.next()) {
            passDb = rs.getString("Password"); // adjust to your DB column
            notFound = 1;
        }

       if (notFound == 1 && Password.equals(passDb)) {
    new Availability().setVisible(true);
    this.dispose();
       } else {
        JOptionPane.showMessageDialog(new JFrame(), "Incorrect ID or Password", "Error", JOptionPane.ERROR_MESSAGE);
            UnameTb.setText("");
            PwordTb.setText("");
            UnameTb.requestFocus(); // Cursor back to username
}

    }
} catch (Exception e) {
    System.out.println("Got it" + e.getMessage());

    
    }//GEN-LAST:event_jButton1ActionPerformed
}*/ private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    String Id = UnameTb.getText(); // User enters ID
    String Password = new String(PwordTb.getPassword()); // User enters Password

    if (Id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "User ID is required", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (Password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Password is required", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String SUrl = "jdbc:mysql://127.0.0.1:3306/car_rental";
    String SUser = "root"; // change if you use a password
    String Spass = "";

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        try (Connection con = DriverManager.getConnection(SUrl, SUser, Spass)) {
            String query = "SELECT Password FROM user WHERE ID = ?";
            java.sql.PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, Id);
            
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String passDb = rs.getString("Password");
                if (Password.equals(passDb)) {
                    // Successful login
                    new Availability().setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Incorrect Password", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "User not found", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    } catch (HeadlessException | ClassNotFoundException | SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
       int z = JOptionPane.showConfirmDialog(null, "Are you sure?", "Select",JOptionPane.YES_NO_OPTION);
       if(z==0){
        System.exit(0);}
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hide;
    private javax.swing.JPasswordField PwordTb;
    private javax.swing.JLabel Show;
    private javax.swing.JTextField UnameTb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private static class PreparedStatement {

        public PreparedStatement() {
        }
    }
}
